CREATE TABLE IF NOT EXISTS `tblitem` (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `code` varchar(255) NOT NULL,
  `price` double(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `product_code` (`code`)
)

;
INSERT INTO `tblproduct` (`name`, `code`, `price`) VALUES
('Channa Bhatura', 'cb', 50.00),
( 'Aloo Ki Tikki', 'akt', 30.00),
( 'Dhokla', 'dkl', 45.00),
( 'Paneer Tikka', 'ptka', 50.00),
( 'Bedmi Puri', 'bpuri', 50.00),
( 'Veg Burger', 'vb', 40.00),
('Vegetable Sandwich', 'vs', 50.00),
( 'Paneer Tikka Sandwich', 'pts', 60.00),
( 'Masala Potato Sandwich', 'mps', 45.00),
( 'White Sauce Cream (Fusilli)', 'wsc', 50.00),
( 'Pink Sauce (Red & White Mix)', 'psrw', 50.00),
( 'Chaat Bhalla Papri', 'cbp', 40.00),
( 'Raj Kachori Chaat', 'rkc', 45.00),
('Golgappa', 'golgpa', 50.00),
( 'Dahi Golgappa', 'dg', 60.00),
( 'Margherita Pizza', 'mpza', 305.00),
( 'Paneer Tikka Pizza', 'ptpza', 350.00),
( 'Deluxe Paneer Pizza', 'dpza', 399.00),
( 'Sambar Vada', 'svda', 60.00),
('Shahi Paneer', 'shpnr', 90.00),
( 'Karahi Paneer', 'kpnr', 80.00),
( 'Mix Veg', 'mixvg', 60.00),
( 'Yellow Dal', 'ydal', 50.00),
( 'Matar Pulao', 'mtrplo', 59.00),
( 'Veg Biryani', 'vgbr', 60.00),
( 'Jeera Rice', 'jraric', 50.00),
( 'Plain Curd', 'plcur', 40.00),
( 'Boondi Raita with Bhalla', 'brwbh', 50.00),
( 'Green Salad', 'slad', 35.00),
( 'Tandoori Roti', 'tnroti', 50.00),
( 'Naan', 'naan', 55.00),
( 'Tandoori Paratha', 'tnprta', 60.00),
( 'Rabri', 'rbri', 35.00),
( 'Gajar Halwa ', 'gjrhla', 50.00),
( 'Kheer', 'kheer', 55.00),
( 'Coffee Pudding', 'copu', 60.00),
( 'Special Veg Thali', 'splvg', 75.00),
( 'Dal Roti', 'dlrti', 50.00),
( 'Rajma Chawal', 'rjchw', 55.00),
( 'Veg Manchurian', 'vgmnu', 90.00),
( 'Hakka Noodles', 'hnood', 75.00),
( 'Mushroom Chilli', 'muschil', 70.00),
( 'Chilli Garlic Chowmein', 'chgcw', 65.00),
( 'Cold Drink', 'coldrnk', 90.00),
( 'Mineral Water', 'mnrlw', 35.00);

		